"""second migration

Revision ID: d7ca1139ab73
Revises: 0ad8689d17bd
Create Date: 2022-03-13 18:01:55.568186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ca1139ab73'
down_revision = '0ad8689d17bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_pic_path')
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
